### ISSUE TITLE
Eon screen goes dark upon being connected to car, OP doesnt engage with cruise control

### ISSUE THREAD

**Issue by darknight111** [hanabi95/kegman#3]
Branch:  untested-0.8.1-devUI-BoltEV-Grey

OP3T eon, grey panda, jshuler giraffe

Devui works fine until it is hooked up on the car. Says pay attention on the road before going completely dark. Restarting car and eon several time doesn't fix problem.

**Comment by hanabi95** [comment]
I will fix this issue after formal release of kegman 0.8.1
