### ISSUE TITLE
kegman-0.8.1-BoltEV-Grey has poor lateral tuning

### ISSUE THREAD

**Issue by darknight111** [hanabi95/kegman#4]
kegman-0.8.1-BoltEV-Grey Line 84 and line 85 have values 
ret.steerRateCost = 2.0
ret.steerActuatorDelay = 0.1

This causes poor lateral behavior on curves at freeway speeds.

It needs to be changed to match kegman-0.8-BoltEV line 84 and 85
ret.steerRateCost = 0.5
ret.steerActuatorDelay = 0.2

In addition, ping pong on freeway straights can be reduced by reducing ret.steerRatio on line 102 to a value slightly less than 16.8. I'm not sure what the best value would be. 

OP3T Eon, Grey Panda, no pedal

**Comment by hanabi95** [comment]
I've updated interface.py same with 0.8.0
